name: CI for main Branch

on:
  pull_request:
    branches: [main]

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from dev branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ Only PRs from dev branch are allowed to merge to main."
            exit 1
          fi

  build-and-test:
    needs: check-pr-source   # <-- Add this line!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file for Docker Compose
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> backend/.env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> backend/.env

      - name: Start backend services
        run: |
          cd backend
          docker compose up -d
          sleep 10  # Wait for services to initialize

      - name: Run company-service tests
        working-directory: backend/company-service
        run: |
          pip install -r requirements.txt
          pytest -s tests/integration -v

      - name: Run categories-service tests
        working-directory: backend/categories-service
        run: |
          pip install -r requirements.txt
          pytest -s tests/integration -v

      - name: Tear down services
        if: always()
        run: cd backend && docker compose down
